### ISSUE TITLE
Enhancement Request - Handling of Text Labels, etc.

### ISSUE THREAD

**Issue by ericmarceau-rogers** [arkanis/process-map#1]
Please allow me to start this by outlining what I imagined as a tool to analyze processes.

I was looking for something to tell me how selected processes were using memory.

Specifically, I was looking for a tool that would show that usage, in 5 distinct groupings, namely:

- RAM-resident (assigned RAM),
- SWAP-resident (RAM-cache),
- SWAP-resident (Disk-cache),
- Disk-resident (source-file), and
- Disk-resident (data or output file(s) )

Maybe I was hoping for too much, but I was looking 
for that monitoring/display to be live and 
for that to be displayed dynamically during the program execution.

I was also hoping that it would be initiated such that the tool would start the process being monitored, such as

> map programName

Regarding specifically this code which you have shared with us, thank you!

I managed to compile this "process-map" tool, and overall I will say that the presented map is quite detailed.  For the tool, the only significant drawback, as-is, is that the text labels, at the higher levels, "hide" some of the finer mapping that is being sought.

I would like to suggest the following for your consideration, and kindly request that you attempt to incorporate those:

- Allow User-selection of text labels for "dynamic" re-positioning.
- Since you "reveal" greater detailed breakdown of memory-block usage as you zoom in, it would also be very helpful to hide labels which are larger, because they hide the smaller partitioning and smaller labels.

Looking at your instructions on the README page, I don't see any visible response to clicking on the "dot".

I attach the build_log.txt file, hoping you might point out what could be done to resolve that aspect of the tool usage.
[build_log.txt](https://github.com/user-attachments/files/16775770/build_log.txt)

Thank you.

**Comment by arkanis** [comment]
Hi Eric,

sounds like you'll be better of with an actual process monitoring tool like `htop`. They're actually made for that purpose while the process map is more of an educational gimmick and experiment I used to learn about hilbert curves and ptrace.

But at least off the top of my head I don't know any tools that provide the information you listed. At least out of the box. Resident set size (the "assigned RAM") is pretty standard, but you probably have to dig a bit for the rest. At least in `htop` the setup page (F2) contains a few columns you might be interested in.

If you want go to deeper the proc(5) man page (`man proc`) is a good source of system and process information that a normal program can read. After a quick look I found "/proc/[pid]/pagemap", a file that contains information for every page (if it's in RAM, in swap, mapped from a file, …). You could write a program that summarizes that. But that sounds very expensive since you would need to iterate over all pages of all memory maps. "/proc/[pid]/smaps" seems more reasonable since it already accumulated the information per memory map and there seems to be a `pmap` command already. I stopped reading after that but there's a lot of interesting stuff in that man page. ;)

About your feature requests (I think):

- Selecting and moving text labels: Sorry, that requires to much code (picking, dragging, tracking positions, etc.).
- Hiding larger labels: Done in commit 2771a45. If a label of a memory map is larger than half the screen it will be hidden.

About clicking on the "dot":

- If you click on a task in the task list at the right of the screen only dots of that task will be shown. Dots of all other tasks will be hidden. Not really useful since every task usually hangs out in poll() or similar places. Only gets interesting when watching CPU heavy processes that don't spend much time waiting. But you can't click on the dots, they're just a particle system visualizing the a few recent instructions a task executed.

Hope that clarifies things a bit. Let me know if it's ok to close the issue.

Happy programming
Stephan

**Comment by ericmarceau-rogers** [comment]
Thank you, Stephan!

Your quick fix on the labels is greatly appreciated. **You can close the issue.**

Regarding the other info, I am grateful for you providing those leads. Those look very interesting and promising.  The **pmap** tool looks like it would offer a lot more than I really want, static-wise.  

Too bad there isn't a **dynamic component** to that, to minimize the overhead to monitor selected elements of such probes.  I'll see what I can come up with that might achieve what I am looking for ... which is really a tool to monitor the impact of changes to the Kernel parameters controlling the Virtual Memory management performance/optimization.  Almost like a dashboard, but specific to that aspect of performance tuning.  I figured that limiting the focus on a single demanding process would allow simplification of the monitoring, enabling me to get a "feel" for how things are interacting, thereby facilitating the optimization process.  As I said, I'll see what I can come up with.

Thank you again for your comments and suggestions.  They are very much appreciated.

**Comment by ericmarceau-rogers** [comment]
Just an FYI.  My own tweak for the decision factor for display.

https://gist.github.com/ericmarceau-rogers/e6d11c4cfe4260ae287ce8a62b3dc6f4

**Comment by arkanis** [comment]
Good idea, I've added variables to adjust when labels and symbols are shown based on your suggestion (commit a099609).
