### ISSUE TITLE
Enhancement Request - Label Overlap - Resolving conflict in placement of Immediate Parent/Child

### ISSUE THREAD

**Issue by ericmarceau-rogers** [arkanis/process-map#2]
The attached image shows the overlap of what I believe to be **3 distinct labels**, but each at a different level in the hierarchy:

![process-map__LabelOverlap](https://github.com/user-attachments/assets/008f1981-90c9-4d07-a2a2-fc446e309e4a)

As can be seen, that overlap creates difficulty in legibility of the labels.  I would like to suggest a (_hopefully simple enough_) approach for the auto-adjustment of the label placement.

When attempting to decide the placement of **label B** (**child of process/object labelled A**), I suggest the shifting of the label B **towards the edge** (top or bottom) **which is closest to the object being labelled**.  The amount of shift would correspond to the **height of the text-box of the parent object's label** (in this case A).

**Comment by arkanis** [comment]
The overlap is caused when multiple symbols point to the same code address. Then multiple labels are drawn with the same bounding box and thus more or less over one another (they're scaled up to fill their bounding box if I remember correctly). In the screenshot there are 3 symbols that shared the same code address (getc, fgetc, _IO_getc), hence being drawn on top of one another.

Avoiding that is somewhat complex because a) you need to detect that case and b) find an arrangement that doesn't overlap the labels and can be associated with the corresponding region on the map. Part a) is merely annoying in C because I'm not sure the symbol list is sorted so you might have to copy, sort, process and then free the whole thing. Part b) however is quite difficult if you want to take it seriously (at least for me). Basically you have an arbitrary shaped outline (in a texture) and try to position a variable number of variable length labels into that outline. And when someone sees the whole thing he should visually associate all the labels with the same thing. For large areas like the memory maps you can assume they're reasonable rectangular and a simple bounding box with a centered text works well enough. For small areas like the symbols this doesn't work all to well however. A "good enough" solution might be to just stack all labels for the same symbols on vertically within the symbols bounding box. That might work well enough.

But personally I don't really want to invest much more work into the process map as it is now. It's nice to look at the first few times but not really useful for deeper inspection. It gets 90% of the "wow" and fun factor while avoiding 90% of the hard problems. Right now it helps to understand the concept of virtual memory (I hope) but is still relatively simple. But that also makes it useless for any real diagnostics or inspection. `htop`, `readelf`, `objdump`, etc. are much faster and more useful for that anyway.

I appreciate you taking a close look at the process map. But making it into something useful probably requires a major rewrite (e.g. for the live-updates and dynamic rearrangements) and solving some hard problems (layouting and arranging stuff). In the end it might be simpler to just approximate all memory regions with rectangles (be it mappings or symbols). That way you could use a box packing algorithm and somehow adapt it to preserve the order. Still a hard problem, but at least a more common one, and easier than having to work with arbitrary outlines. Right now the code uses hilbert curves to map 1D ranges into 2D pixel areas (that are all those textures). Somewhat pretty to look at but a pain down the line for layouting and similar stuff.

**Comment by ericmarceau-rogers** [comment]
Thank you for taking the time to explain the rationale behind your decision.  It is much appreciated.
